### ISSUE TITLE
Document aligner compilation fails after #170

### ISSUE THREAD

**Issue by zuny26** [bitextor/bitextor#172]
After pull request #170 c++ document aligner compilation fails with the following error:
```
[ 44%] Linking CXX executable bin/ngram_test
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ngram_test.dir/build.make:163: bin/ngram_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/ngram_test.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```
CMake finishes without errors. gcc version is 9.2.1 and Boost version is 1.67.0

**Comment by jelmervdl** [comment]
I was fighting with this error this morning as well. I haven't found a solution yet, but I've implemented the option to skip building the test cases in #173 . After that running cmake with `-DBUILD_TESTING=OFF` should stop it from breaking the build at least.

**Comment by lpla** [comment]
Closed #172 via https://github.com/bitextor/bitextor/commit/bcd1d896e82ddb7e891cc4d560f8418d5ff1945b.
